products:
  duo-bot:
    build:
      main-pkg: ./main
      version-var: github.com/palantir/duo-bot/cmd.version
      environment:
        CGO_ENABLED: "0"
      os-archs:
      - os: linux
        arch: amd64
    dist:
      disters:
        bin:
          type: bin
    publish: {}
product-defaults:
  publish:
    group-id: com.palantir.duo-bot
